### ISSUE TITLE
[Bug] Recently played champions showed in profile is incorrect.

### ISSUE THREAD

**Issue by SadmanTariq** [molenzwiebel/OriannaBot#65] opened 2024-07-24 07:42 UTC
The three most recently played champions showed in the profile command is incorrect.

![image](https://github.com/user-attachments/assets/537a6d7e-71cb-41ba-9912-eab73b300cdf)

**Comment by molenzwiebel** [comment] 2024-07-24 10:32
The most recently played champions are displayed as the most recent stat updates observed by Orianna. Based on downtimes/just having an account added those will be incorrect. This is a limitation by design.

**Closed by molenzwiebel** 2024-07-24 10:32 UTC
